FROM alpine:edge

LABEL "MAINTAINER"="icaoberg"
LABEL "EMAIL"="icaoberg@psc.edu"
LABEL "SUPPORT"="help@psc.edu"
LABEL "REPOSITORY"="http://github.com/pscedu/singularity-ffmpeg"
LABEL "COPYRIGHT"="Copyright © 2022-2024 Pittsburgh Supercomputing Center. All Rights Reserved."
LABEL "VERSION"="6.1.1"

RUN apk add --update ffmpeg=6.1.1
